name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up Node.js  
        uses: actions/setup-node@v2  
        with:  
          node-version: '16'  # Utilisez la version de Node.js appropriée pour votre projet  
  
      - name: Restore frontend npm packages  
        run: |  
          cd frontend  
          npm install  
  
      - name: Build frontend  
        run: |  
          cd ./frontend  
          npm run build  
  
      - name: Set up Python  
        uses: actions/setup-python@v2  
        with:  
          python-version: '3.12'  # Utilisez la version de Python appropriée pour votre projet  
  
      - name: Restore backend python packages  
        run: |  
          cd ../backend  
          pip install -r requirements.txt  
  
      - name: Start backend  
        run: |  
          nohup python app.py &  # Démarre le backend en arrière-plan  
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_SMOKE_0530A820F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./app" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_SMOKE_0530A820F }}
          action: "close"
